chromedriver: C:\Program Files (x86)\chromedriver.exe
user_data_dir: C:\Users\jande\AppData\Local\Google\Chrome\User Data\
workspace_name: international_business_community
profile: ["Profile 3", "Profile 1"]
nxt_btn_css: "#pagination > div > div > button:"


csv_path: selenium/outputs/
workspace_url: https://app.slack.com/client/T06HKSK2L
group_name: MSPTech
